### ISSUE TITLE
AWS::EKS::FargateProfile

### ISSUE THREAD

**Issue by akshayvvr** [aws-cloudformation/aws-cloudformation-coverage-roadmap#441] opened 2020-04-09 22:06 UTC
1. Title
AWS::EKS::FargateProfile

2. Scope of request
AWS::EKS::FargateProfile will enable us to create a fargate profile to an EKS Cluster. It is supported in boto3 but not CloudFormation

3. Expected behavior
Allow users to create and attach a Fargate profile to an EKS Cluster

Type: AWS::EKS::FargateProfile
Properties: 
  Name: String
  ClusterId: <>

4. Suggest specific test cases
Want to be able to create Fargate profiles using cloudformation
As alternative, many are using awscli and terraform.

5. Helpful Links to speed up research and evaluation
EKS API Reference
https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html

6. Category
Compute (EKS)

**Comment by eduardomourar** [comment] 2020-05-02 20:28
I believe this is a duplicate of #288

**Comment by PatMyron** [comment] 2020-09-10 17:40
[`AWS::EKS::FargateProfile`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-fargateprofile.html)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Closed by PatMyron** 2020-09-10 17:40 UTC
Labels: compute
