### ISSUE TITLE
New pseudo parameter reference: AWS::OrgId

### ISSUE THREAD

**Issue by pierresteiner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#182] opened 2019-09-18 08:43 UTC
Referencing The AWS Organization id from CF using this new pseudo parameter would be really convenient.

This could enable sharing resources (s3, lambda, ...) more efficiently to multiple accounts

**Comment by TheDanBlanco** [comment] 2019-09-19 00:19
this looks like a duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/160. please re-open if this isn't the case.

**Closed by TheDanBlanco** 2019-09-19 00:19 UTC
