### ISSUE TITLE
Feature Request: Add EFS support for AWS CodeBuild using CloudFormation

### ISSUE THREAD

**Issue by NujellaKarthik** [aws-cloudformation/aws-cloudformation-coverage-roadmap#381] opened 2020-02-14 21:32 UTC
Feature Request: Add EFS support for AWS CodeBuild using CloudFormation

https://aws.amazon.com/about-aws/whats-new/2020/02/aws-codebuild-adds-support-for-amazon-efs/

**Comment by luiseduardocolon** [comment] 2020-02-18 02:09
Duplicate of #374 - closing

**Closed by luiseduardocolon** 2020-02-18 02:09 UTC
Labels: dev tools, duplicate
