### ISSUE TITLE
AWS::Events::Rule->EventPattern - Ability to supply a integer value

### ISSUE THREAD

**Issue by Guslington** [aws-cloudformation/aws-cloudformation-coverage-roadmap#251] opened 2019-11-06 00:45 UTC
## 1. Title
AWS::Events::Rule->EventPattern - Ability to supply a integer value

## 2. Scope of request 
Ability to supply a integer value in a cloudwatch event pattern

## 3. Expected behavior

On create or update supply a integer value in a cloudwatch event pattern, however cloudformation converts that value to a string. Integer values are required for guardduty severity.

## 4. Suggest specific test cases

Example event pattern for guardduty

```json
{
      "detail-type": [
        "GuardDuty Finding"
      ],
      "source": [
        "aws.guardduty"
      ],
      "detail": {
        "severity": [
          5,8
        ]
    }
}
```

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_cloudwatch.html#guardduty_cloudwatch_example

**Comment by michaelwittig** [comment] 2020-02-05 07:55
This bug get's more relevant with the new filter capabilities:

```yaml
  ECRIMageScanFindingEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
        - 'aws.ecr'
        'detail-type':
        - 'ECR Image Scan'
        detail:
          finding-severity-counts:
            CRITICAL: [{exists: false}, {numeric: ['>', 0]}]
            HIGH: [{exists: false}, {numeric: ['>', 0]}]
            MEDIUM: [{exists: false}, {numeric: ['>', 0]}]
            UNDEFINED: [{exists: false}, {numeric: ['>', 0]}]
```

is turned into:
```json
{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "finding-severity-counts": {
      "HIGH": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ],
      "MEDIUM": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ],
      "UNDEFINED": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ],
      "CRITICAL": [
        {
          "exists": "false"
        },
        {
          "numeric": [
            ">",
            "0"
          ]
        }
      ]
    }
  }
}
```

which results in all kinds of validation errors.

instead of:

```json
{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "finding-severity-counts": {
      "HIGH": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "MEDIUM": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "UNDEFINED": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ],
      "CRITICAL": [
        {
          "exists": false
        },
        {
          "numeric": [
            ">",
            0
          ]
        }
      ]
    }
  }
}
```

**Comment by jogold** [comment] 2020-02-12 16:21
@TheDanBlanco any update on this? Really frustrating to see that the [new advanced event patterns](https://aws.amazon.com/blogs/compute/reducing-custom-code-by-using-advanced-rules-in-amazon-eventbridge/) cannot be deployed via CloudFormation.

**Comment by TheDanBlanco** [comment] 2020-02-12 19:04
nothing yet. there are other items with higher +1's that we're working on right now. i'll keep an eye on this though

**Comment by jogold** [comment] 2020-02-13 17:17
Thanks for the feedback @TheDanBlanco.

Just to be clear, it's not really a coverage issue here but rather a bug. CloudFormation stringifies everything in `AWS::Events::Rule.EventPattern` (numbers, booleans) and this leads to validation errors from CloudWatch Events.

**Comment by jmnarloch** [comment] 2020-02-24 01:48
I had created initial pull request for dedicated builder: https://github.com/aws/aws-cdk/pull/6414

**Comment by stevecaldwell77** [comment] 2020-03-09 17:52
@TheDanBlanco: the example by @michaelwittig above shows that this issue is not just integers, but booleans too. Just wanted to explicitly call that out so it didn't go unnoticed! Not being able to use an exists pattern is really limiiting.

**Comment by jackcbrown89** [comment] 2020-03-19 14:57
@TheDanBlanco Any status updates on a fix for this? This blocks us from writing many of our event patterns in CF templates.

**Comment by ljacobsson** [comment] 2020-04-09 08:43
Also interested in an update on this. EventBridge is a very potent service, but this bug makes it very unattractive to adopt for any team. We're ending up writing ugly workarounds which is getting painful. 

Imho this is more of a bug than a feature request and there must be internal interest from the EventBridge team to get this fixed. Is it solely prioritised based on upvotes or do we have a chance to see this fixed in the near future?

**Comment by stevecaldwell77** [comment] 2020-04-09 16:01
@ljacobsson - a fix is supposedly rolling out: https://twitter.com/nickste/status/1237036312571437059

**Comment by ljacobsson** [comment] 2020-04-09 23:28
@stevecaldwell77 yes I was following the rollout of that one, but it got pulled back. 

I'm tracking this through various threads and just learnt from  [here](https://github.com/awslabs/serverless-application-model/issues/1455) that a fix is rolling out very soon 👍

**Comment by ritchieleeann** [comment] 2020-05-15 17:53
Any updates on this? That Twitter thread said there'd be **another** update on ETA last week.

**Comment by sukdeb-gitlab** [comment] 2020-06-04 01:43
I can confirm the above pattern works as expected now, probably the fix has been applied:-
{
      "detail-type": [
        "GuardDuty Finding"
      ],
      "source": [
        "aws.guardduty"
      ],
      "detail": {
        "severity": [
          5,8
        ]
    }
}

**Comment by michaelwittig** [comment] 2020-06-04 06:29
I can not confirm that it works.

Pattern:
```yaml
EventPattern:
  source:
  - 'aws.ecr'
  'detail-type':
  - 'ECR Image Scan'
  detail:
    finding-severity-counts:
      CRITICAL: [{exists: false}, {numeric: ['>', 0]}]
      HIGH: [{exists: false}, {numeric: ['>', 0]}]
      MEDIUM: [{exists: false}, {numeric: ['>', 0]}]
      UNDEFINED: [{exists: false}, {numeric: ['>', 0]}]
```

Error:

Event pattern is not valid. Reason: exists match pattern must be either true or false. at [Source: (String)"{"detail-type":["ECR Image Scan"],"source":["aws.ecr"],"detail":{"finding-severity-counts":{"HIGH":[{"exists":"false"},{"numeric":[">","0"]}],"MEDIUM":[{"exists":"false"},{"numeric":[">","0"]}],"UNDEFINED":[{"exists":"false"},{"numeric":[">","0"]}],"CRITICAL":[{"exists":"false"},{"numeric":[">","0"]}]}}}"; line: 1, column: 112] (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: InvalidEventPatternException; Request ID: d4f20cd8-1edc-4e63-b55b-ab7339111615)
--

**Comment by belangovan** [comment] 2020-06-17 11:27
still its not fixed, 
"containers": {
      "exitCode": [
        "1",
        "2"
      ]
    },
kindly confirm fix, we are blocked with this issue

**Comment by codesmithtech** [comment] 2020-07-07 16:27
Confirmed as not working with booleans when using the latest version of the AWS CLI

**Comment by shakyaabiral** [comment] 2020-07-30 07:05
Using cdk, the cloudformation json template is generated well, 
"containers": {
                          "exitCode": [
                            1,
                            2
]
}
but the is converted to strings on deployment.
Waiting for updates...

**Comment by wintersky** [comment] 2020-08-07 17:54
This may be fixed at least for integers. On August 6th I observed a stack with detail: numeric: ["<", 3] produce a rule which looks correct: "numeric": ["<",  3] and which works properly in testing.

**Comment by michaelwittig** [comment] 2020-08-08 05:01
I can confirm the fix

**Comment by KIVagant** [comment] 2020-08-13 17:24
Inability to use boolean values for boolean parameters for years is ridiculous.

**Comment by shihrer** [comment] 2020-08-13 21:03
Are boolean values still not working?  I haven't had a chance to check since we haven't had to deploy any rules with boolean values yet.  CloudFormation bugs with event patterns have been a bit of a pain for us.

**Comment by fitzplb** [comment] 2020-08-24 10:06
@ljacobsson I think you're right I've just tried it in eu-west-1 and it works fine. Thanks for the tip about simplifying the event pattern, the docs don't have that (https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_cloudwatch.html)

**Comment by fitzplb** [comment] 2020-08-24 10:30
@ljacobsson actually if I use your event pattern Cloudformation renders the integers correctly without quotes

**Comment by serverlesspolska** [comment] 2020-12-03 16:30
It does not work for me in Oregon and N.Virginia regions.

I have following CF excerpt (it's a part of huge CF Template generated by Serverless Framework)
```
"EventBridgeConfig": {
          "RuleName": "test-event-bridge-lambda-dev-myFunction-rule-1",
          "EventBus": "ServiceBusArn...",
          "Pattern": {
            "source": [
              "my-source"
            ],
            "detail-type": [
              "EVENT_TYPE"
            ],
            "detail": {
              "entityId": [
                {
                  "numeric": [
                    {
                      "=": 159
                    }
                  ]
                }
              ]
            }
          }
```

And CF is failing with 
```
Failed to create resource. Event pattern is not valid. 
Reason: Invalid member in numeric match: {
   at [Source: (String)"{
               "detail-type":["EVENT_TYPE"],
               "source":["my-source"],
               "detail":{ 
                     "entityId":[{"numeric":[{"=":"159"}]}]
  }
}
"; line: 1, column: 126]
```

**Comment by ljacobsson** [comment] 2020-12-03 20:08
@serverlesspolska what does Custom::EventBridge do? I guess that's stringifying all values.

Tried using [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html)?

**Comment by serverlesspolska** [comment] 2020-12-04 11:33
@ljacobsson I'm caught between you and Serverless Framework
There is an issue: https://github.com/serverless/serverless/issues/7506#issuecomment-738100855 and they blame CloudFormation. 

To be honest I don't know what `Custom::EventBridge`does - it's generated by the framework - but it's part of CloudFormation. And for sure it has a number not string. So it looks like they are right.

Yes, I could use `AWS::Events::Rule` but the whole point of using Serverless Framework is that it generates a lot of IaC for us. In fact, we are using now `AWS::Events::Rule` as a workaround solution, but it leads to a lot of additional code instead of several lines in our `Yaml` template.

**Closed** 2021-03-19 06:06 UTC
Labels: app integration
