### ISSUE TITLE
AWS::EC2::VPNConnection-TransitGatwayAttachment-New Attribute

### ISSUE THREAD

**Issue by manuelcoppotelli** [aws-cloudformation/aws-cloudformation-coverage-roadmap#220] opened 2019-10-15 10:49 UTC
Quick Sample Summary:
1. Title -> AWS::EC2::VPNConnection-TransitGatwayAttachment-New Attribute
2. Scope of request -> `AWS::EC2::VPNConnection` resource with property `TransitGatewayId` specified creates the `TransitGatwayAttachment`, this should be available via Fn::GetAtt
3. Expected behavior -> In Create, it should returns another attribute containing the TransitGatwayAttachment id, so that `!GetAtt VPNConnection.TransitGatwayAttachment` returns the id of the attachment just created.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> Networking & Content
7. Any additional context (optional)

**Comment by PatMyron** [comment] 2020-09-03 17:54
looks like a duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/183

**Closed by PatMyron** 2020-09-03 17:54 UTC
Labels: compute, enhancement
