### ISSUE TITLE
[AWS::QuickSight::VPCConnection] - [BUG] - Performing GET on CREATE

### ISSUE THREAD

**Issue by Rizxcviii** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2107] opened 2024-08-15 11:51 UTC
### Name of the resource

AWS::QuickSight::VPCConnection

### Issue Description

When creating a VPC Connection, it performs a call similar to a GET request, rather than trying to create the VPC.

### Expected Behavior

Creates a VPC using the resource properties

### Observed Behavior

Tries to get a current VPC connection with the specified `vpcConnectionId`

> VPCConnection Resource handler returned message: "Resource of type 'AWS::QuickSight::VPCConnection' with identifier 'us-east-1-test' was not found." (RequestToken: xxxxxxxxxxxxxxxxxxxxxx, HandlerErrorCode: NotFound)

### Test Cases

This was done in TypeScript using the CDK, but it was an L1 construct, so directly called within CloudFormation. Trying to create this will instead try to get a current VPC with the `vpcConnectionId`

```ts
new quicksight.CfnVPCConnection(this, 'VPCConnection', {
  name: 'VPC Connection',
  vpcConnectionId: 'us-east-1-test',
  subnetIds: [subnet.subnetId],
  roleArn: role.roleArn,
  securityGroupIds: [securityGroup.securityGroupId],
  awsAccountId: this.account,
});
```

**Comment by alanrdze** [comment] 2024-09-09 18:24
Hi, 

This is intended behavior coming from Cloudformation.

From the error you referencing to, Cloudformation is failing due to its inability to find the dependent resource within your account: `us-east-1-test`

Cloudformation verifies dependent resources before attempting to create the resource in question by calling a GET operation, if these resources exist, then cloudformation proceeds with the creation workflow.

To avoid this error within your CDK application, please add a reference to vpcConnectionId to its dependent resource. This will avoid CDK/CFN attempting to locate a resource that may have not been created in time, or alternatively make sure the vpc Connection exists with the name `us-east-1-test` within your account.

Closing this issue as this is expected behavior.

**Closed as completed by alanrdze** 2024-09-09 18:24 UTC
Labels: bug

**Comment by kyleplant** [comment] 2025-01-14 06:13
This is a weird one. I had this working in prior stack creations but currently this does not work. 

Isn't the dependent resource the one being deployed? ie. Giving the [CfnVPCConnection an identifier](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateVPCConnection.html#QS-CreateVPCConnection-request-VPCConnectionId)? Perhaps the idea was to lookup the ID and check if it already exists and fail, not the other way round?

It seems that it must be set.

VpcConnection Resource handler returned message: "1 validation error detected: Value null at 'vPCConnectionId' failed to satisfy constraint: Member must not be null (Service: QuickSight, Status Code: 400, Request ID: 17ffe06b-60dc-481d-8996-ae5fc2eba7e8)" (RequestToken: 1caac790-b87c-7d62-fdd4-7a1798f496e2, HandlerErrorCode: GeneralServiceException)

**Comment by kyleplant** [comment] 2025-01-14 06:37
Ah, the missing resource is in fact the account subscription which would need a custom resource. https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateAccountSubscription.html
