### ISSUE TITLE
AWS::Logs::LogGroup support for tagging

### ISSUE THREAD

**Issue by ctaintor** [aws-cloudformation/aws-cloudformation-coverage-roadmap#237] opened 2019-10-22 21:32 UTC
#### Scope of Request

AWS::Logs::LogGroup does not support tagging today

#### Expected behavior

In Create, I should be able to set tags for the log group

#### Links to existing API doc

https://docs.aws.amazon.com/cli/latest/reference/logs/tag-log-group.html

#### Category tag

CloudWatch

**Comment by PatMyron** [comment] 2019-10-22 21:38
closing as duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/77

**Closed by PatMyron** 2019-10-22 21:38 UTC
