### ISSUE TITLE
AWS::ServiceCatalog::PortfolioShare - [Coverage] - Add OrganizationNode property

### ISSUE THREAD

**Issue by seb-steuer** [aws-cloudformation/aws-cloudformation-coverage-roadmap#2174] opened 2024-11-06 15:36 UTC
### Name of the resource

AWS::ServiceCatalog::PortfolioShare

### Description

The AWS::ServiceCatalog::PortfolioShare CloudFormation resource type is missing OrganizationNode property.

API reference:
https://docs.aws.amazon.com/servicecatalog/latest/dg/API_CreatePortfolioShare.html#servicecatalog-CreatePortfolioShare-request-OrganizationNode

**Comment by AlexChesters** [comment] 2024-11-21 11:49
is this a duplicate of #594 ?

**Comment by seb-steuer** [comment] 2024-11-21 12:07
> is this a duplicate of #594 ?

yes, I've looked but havent seen that issue for some reason. This can be closed then. I have voted in the #594

**Closed as not planned** 2024-11-22 11:22 UTC
Labels: Coverage
