### ISSUE TITLE
AWS::CloudFormation::Stack-Nested-Change Set

### ISSUE THREAD

**Issue by manuelcoppotelli** [aws-cloudformation/aws-cloudformation-coverage-roadmap#221] opened 2019-10-15 11:00 UTC
1. Title -> AWS::CloudFormation::Stack-Nested-Change Set
2. Scope of request -> AWS::CloudFormation::Stack-Nested Computing the ChangeSet for a Stack with nested templates, does not return the changes of need stacks
3. Expected behavior -> The computed ChangeSet contains also the changes performed by the nested stacks templates.
4. Test case recommendation (optional) ->
5. Links to existing API doc (optional) ->
6. Category tag (optional) -> Management
7. Any additional context (optional)

**Comment by PatMyron** [comment] 2019-10-16 22:33
closing as a duplicate of #142

**Closed by PatMyron** 2019-10-16 22:33 UTC
