### ISSUE TITLE
AWS::CloudFormation::DeleteStack is taking more than 30mins in us-west-2

### ISSUE THREAD

**Issue by gu3sss** [aws-cloudformation/aws-cloudformation-coverage-roadmap#414] opened 2020-03-10 16:07 UTC
#### AWS::CloudFormation::DeleteStack 
is taking more than 30mins in us-west-2

## 2. Scope of request 
AWS::CloudFormation::DeleteStack:: When trying to delete a cloudformation stack built using Serverless, takes more than 30 mins to complete. Gets stuck in the event "CloudFormation is waiting for NetworkInterfaces associated with the Lambda Function to be cleaned up." Typically happens only when the lambda function created as part of this stack is inside a VPC.

## 3. Expected behavior
Cloudformation stack deletes should complete sooner, like how it does if lambda function is not part of a VPC.

## 4. Suggest specific test cases
- Create a cloudformation stack to build a lambda function inside a VPC in us-west-2
- Try deleting the stack after its built and ready for use

## 5. Helpful Links to speed up research and evaluation
This issue seems to be a known issue mentioned in the blog,
https://aws.amazon.com/blogs/compute/announcing-improved-vpc-networking-for-aws-lambda-functions/
Nonetheless, this behavior shouldn't happen now per the update on November 25 2019, which states,
"We have fully rolled out the changes to the following additional Regions to those mentioned below: US East (N. Virginia), US West (Oregon), Canada (Central), EU (London), EU (Stockholm), and Asia Pacific (Hong Kong). All AWS accounts in these Regions will see the improvements outlined in the original post."
Raised a case with AWS support (#6864542381) and the support person confirmed that it is still an open issue for few and is being actively investigated by the service team.

## 6. Category
Compute
Networking & Content

**Comment by TheDanBlanco** [comment] 2020-03-16 16:40
this seems to be a duplicate of #392

**Closed by TheDanBlanco** 2020-03-16 16:40 UTC

**Comment by ronkorving** [comment] 2021-10-14 04:13
@TheDanBlanco  Yeah, and it was ignored there too. This is a known issue. Known by everyone using Lambdas in VPC anyway, so I can't imagine AWS is unaware.
