### ISSUE TITLE
Native AWS::StackSet::* Resource

### ISSUE THREAD

**Issue by ngamradt-turner** [aws-cloudformation/aws-cloudformation-coverage-roadmap#362] opened 2020-02-03 15:23 UTC
## 1. Title 

A new AWS::StackSet::* Resource should be created.

## 2. Scope of request 

Currently there exists a custom resource that allows people to create StackSets using CloudFormation:

https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/solutions/StackSetsResource

## 3. Expected behavior

Everything I can do with StackSets in the Console and in the Custom Resource should be supported natively in CloudFormation.

## 4. Suggest specific test cases

I should be able to create, delete, and manage CloudFormation StackSets via CloudFormation.

## 5. Helpful Links to speed up research and evaluation

1. https://aws.amazon.com/blogs/mt/building-an-aws-cloudformation-custom-resource-to-manage-stacksets/
2. https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/solutions/StackSetsResource

Use the categories as displayed in the AWS Management Console (simplified):

11. Other

**Comment by jplock** [comment] 2020-02-03 15:51
Duplicate of #102 and #103?

**Closed** 2020-02-03 19:23 UTC

**Comment by ngamradt-turner** [comment] 2020-02-03 21:14
My apologies regarding the duplicate.  I am usually good at checking for duplicates first but didn't do so this time around.
