### ISSUE TITLE
AWS::CodeDeploy::DeploymentGroup-DeploymentType Support BLUE_GREEN also for ECS/Fargate

### ISSUE THREAD

**Issue by pgarbe** [aws-cloudformation/aws-cloudformation-coverage-roadmap#37] opened 2019-07-31 07:15 UTC
1. Title -> AWS::CodeDeploy::DeploymentGroup-DeploymentType
2. Scope of request -> AWS::CodeDeploy::DeploymentGroup-DeploymentType supports BLUE_GREEN for Lambda but not for ECS/Fargate.
3. Expected behavior -> BlueGreen deployments for ECS/Fargate services.
5. Links to existing API doc (optional) -> Announcement: https://aws.amazon.com/blogs/devops/use-aws-codedeploy-to-implement-blue-green-deployments-for-aws-fargate-and-amazon-ecs/
6. Category tag (optional) -> Compute
7. Any additional context (optional) -> Same request as in Containers Roadmap: https://github.com/aws/containers-roadmap/issues/130

**Comment by jk2l** [comment] 2019-07-31 08:45
I don't think AWS Blue/Green is compatible with CloudFormation. When CodeDeploy deploy in Blue/Green. it create a new AutoScaling group and then on completed it delete the old AutoScaling group. it is a hard delete and unrecoverable. 

This mean managing AutoScaling group with CloudFormation with CodeDeploy Blue/Green does not work well. Because when you try to update your AutoScaling group (e.g. update the LaunchConfiguration) it will say the AutoScaling group does not exist and just simply fail

**Comment by steven-cuthill-otm** [comment] 2019-08-02 09:51
This has 62 links on the  Containers Roadmap: aws/containers-roadmap#130 and it has been a big issue for mission critical deployments on ECS with cloud-formation. this can be done with other non aws toolsets.

**Comment by stefanorg** [comment] 2019-08-12 17:44
👍

**Comment by JoeAlamo** [comment] 2019-12-20 14:11
Super excited you are working on this 😃

**Comment by labnux** [comment] 2020-02-07 12:26
Way to go @luiseduardocolon !
A bit blocked about this in my PoC for a fully automated, within CloudFormation, CodePipeline pipeline with ECS Fargate as the target across multiple environments.

**Comment by miguelsanchez-eb** [comment] 2020-03-24 09:41
Looking forward to this so much. Please, let us know as soon as you release something.

**Comment by clareliguori** [comment] 2020-05-19 21:22
You can now use CloudFormation to perform Amazon ECS blue/green and canary deployments through AWS CodeDeploy!  To learn more visit [the announcement](https://aws.amazon.com/about-aws/whats-new/2020/05/aws-cloudformation-now-supports-blue-green-deployments-for-amazon-ecs/) and the [user guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html).

Note: This issue and #56 still call out valid coverage gaps for using CloudFormation to create a CodeDeploy deployment group, where that deployment group will then be used for doing ECS blue-green deployments directly with CodeDeploy *outside* of CloudFormation (as described in https://aws.amazon.com/blogs/devops/use-aws-codedeploy-to-implement-blue-green-deployments-for-aws-fargate-and-amazon-ecs/).  

The new feature released today is used for doing an ECS blue-green deployment during a CloudFormation stack update, orchestrated by CodeDeploy; it is not for doing an ECS blue-green deployment outside of CloudFormation.  It doesn't require a `AWS::CodeDeploy::DeploymentGroup` resource in the template; instead it uses a new 'Hooks' section in the template for specifying deployment settings.

**Comment by konstantinj** [comment] 2020-05-19 22:06
@clareliguori That means CloudFormation can now do with ECS exactly what CodeDeploy was already capable of but CloudFormation is not using any CodeDeploy resources for that?

**Comment by clareliguori** [comment] 2020-05-19 22:16
It still uses CodeDeploy under the hood and follows the same steps as direct CodeDeploy blue-green deployments.  It just doesn't require any explicit CodeDeploy resources to be created in the template; instead it is configured via the Hooks and Transform sections.  There are some slight differences between the two 'modes': for example, instead of configuring alarms to watch for rollback in CodeDeploy, you configure them on your CloudFormation stack and CFN monitors and rolls back the template.

There is an example template here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html#blue-green-template-example

**Comment by pgarbe** [comment] 2020-05-20 05:37
@clareliguori Can you explain what the new 'Hooks' section is doing? How is it different to 'Transforms'?

**Comment by mattias-fjellstrom** [comment] 2020-05-20 07:21
@clareliguori There are no alarms defined in the example you linked to. Are you saying that if I define an alarm in the same stack as the blue/green resources and then perform a stack update it will work similar to when I tell CodeDeploy to watch an alarm during a deployment?

**Comment by mattias-fjellstrom** [comment] 2020-05-20 07:52
Has anyone successfully tested this using an NLB instead of an ALB? 

I've adjusted the example provided in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html#blue-green-template-example to use an NLB. The template I use is available here https://github.com/mattias-fjellstrom/ecs-blue-green/blob/master/templates/ecs-blue-green-nlb.yml 
I am able to create the stack successfully, but when I perform an update (in this case modifying task cpu/memory resources to force a replacement of the task definition) I get an error saying `'CodeDeployBlueGreenHook' of type AWS::CodeDeploy::BlueGreen failed with message: Internal failure.`. Not much to go on.

**Comment by clareliguori** [comment] 2020-05-20 16:18
@mattias-fjellstrom re: alarms: No, alarms defined in the stack template are not automatically monitored.  CloudFormation has a 'rollback triggers' feature to configure a list of pre-existing alarms that CFN should watch and rollback stack updates on:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-rollback-triggers.html

I have asked the team to take a look at the Internal failure you're seeing

**Comment by vladiscovery** [comment] 2020-05-20 21:18
> You can now use CloudFormation to perform Amazon ECS blue/green and canary deployments through AWS CodeDeploy! To learn more visit [the announcement](https://aws.amazon.com/about-aws/whats-new/2020/05/aws-cloudformation-now-supports-blue-green-deployments-for-amazon-ecs/) and the [user guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html).

We followed the example provided. The stack was created successfully, but when we tried to update task definition (cpu/memory) we got error:
```
'CodeDeployBlueGreenHook' of type AWS::CodeDeploy::BlueGreen failed with message: The TaskDefinition logical Id [BlueTaskDefinition] is the same between initial and final template, CodeDeploy can't perform BlueGreen style update properly

**Comment by KiamarzFallahi** [comment] 2020-05-20 21:20
@mattias-fjellstrom Re: NLB vs ALB. 

Yes, NLB is supported, but only with AllAtOnce traffic routing config. The template you provided is setup properly. I don't see any apparent issues. 

I can look into the "Internal Failure" you are facing if you can DM me your CodeDeploy deployment ID, Account ID and CloudFormation Stack ID.

**Comment by vladiscovery** [comment] 2020-05-21 20:03
Updates to TaskDefinition are failing cloudformation stack update. Here is another topic about it on [aws forum](https://forums.aws.amazon.com/thread.jspa?messageID=943909&tstart=0)
I found that if using an example from the official user guide, only updates to TaskSet are triggering blue/green deployment without CloudFormation error. But it's actually useless as we need to trigger blue/green deployment after TaskDefinition was changed (by changing the image, cpu, memory, environment variables etc).

**Comment by luiseduardocolon** [comment] 2020-05-22 16:28
Will close this issue, although we understand there might be specific use cases not covered here.  Feel free to open new issues for those use cases specifically so we can track them individually, and we'll keep an eye out for them.

**Closed by luiseduardocolon** 2020-05-22 16:28 UTC
Labels: dev tools, enhancement

**Comment by anugarg07** [comment] 2020-05-27 23:11
> > You can now use CloudFormation to perform Amazon ECS blue/green and canary deployments through AWS CodeDeploy! To learn more visit [the announcement](https://aws.amazon.com/about-aws/whats-new/2020/05/aws-cloudformation-now-supports-blue-green-deployments-for-amazon-ecs/) and the [user guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html).
> 
> We followed the example provided. The stack was created successfully, but when we tried to update the task definition (CPU/memory) we got an error:
> 
> ```
> 'CodeDeployBlueGreenHook' of type AWS::CodeDeploy::BlueGreen failed with message: The TaskDefinition logical Id [BlueTaskDefinition] is the same between initial and final template, CodeDeploy can't perform BlueGreen style update properly
> ```

Can you check if you added the "Transform" section in your template, in addition to "Hooks" section. As called out in public docs, both of these sections are needed for CD B/G deployments for ECS

Add a reference to the AWS::CodeDeployBlueGreen transform to your template:

    "Transform": [
        "AWS::CodeDeployBlueGreen"
    ],

**Comment by anugarg07** [comment] 2020-05-27 23:14
> Updates to TaskDefinition are failing cloudformation stack update. Here is another topic about it on [aws forum](https://forums.aws.amazon.com/thread.jspa?messageID=943909&tstart=0)

It should work for TaskDefinition updates as well. Can you post the issue  (if different from above) you are seeing?

**Comment by vladiscovery** [comment] 2020-05-28 17:06
I did use the same example you suggested. `Transform` section is in the template. The Blue/Green deployment is triggering only with TaskDefinition image changes. Changes to task definition environment variables or to cpu/memory are not triggering the deployment and stack update failing with an error above.

**Comment by henrik-utter-wcar** [comment] 2020-06-04 09:48
> I can look into the "Internal Failure" you are facing if you can DM me your CodeDeploy deployment ID, Account ID and CloudFormation Stack ID.

I am experiencing the exact same thing when trying to use an NLB, i.e. error message `'CodeDeployBlueGreenHook' of type AWS::CodeDeploy::BlueGreen failed with message: Internal failure.`
Did you get anywhere on this? @mattias-fjellstrom @KiamarzFallahi

**Comment by mattias-fjellstrom** [comment] 2020-06-04 11:16
@henrik-utter-wcar I actually sent the question to the AWS business support, the relevant part of the answer is this:

> This behaviour can be resolved by providing a test listener and specifying it in the TestTrafficRoute section of the Blue/Green hook section of the CloudFormation template:

            TrafficRouting:
              ProdTrafficRoute:
                Type: 'AWS::ElasticLoadBalancingV2::Listener'
                LogicalID: NLBListenerProdTraffic
              TestTrafficRoute:
                Type: 'AWS::ElasticLoadBalancingV2::Listener'
                LogicalID: NLBListenertestTraffic

They say this is a workaround, and that the underlying issue will be resolved at some point (not able to give an estimate).

I tried the workaround, and it works, however: the behavior during the deployment is not very good. It seems like you get a downtime of 1 to several minutes after the target group is switched. Let me know if you see any different behavior, I only spent an hour investigating without getting anywhere.

**Comment by henrik-utter-wcar** [comment] 2020-06-04 12:56
Thanks @mattias-fjellstrom. I will give that a shot, but I assume I will see the same behavior then.
I have experienced similar downtime when doing Blue/Green deployments using CodeDeploy + NLB from the cli as well. ALB always works like a charm.

**Comment by henrik-utter-wcar** [comment] 2020-06-04 15:04
@mattias-fjellstrom It seems like we are in the same boat, that is exactly the setup I'm struggling with as well. I also had high hopes for this feature, but I can also verify now that it is still the same issue with the NLB.
I have previously tried using BeforeAllowTraffic/AfterAllowTraffic hooks to control the behavior during deployment, but can't get that to work in a reliable way either. It seems we need to wait for better support in NLB for this to work properly.

**Comment by jmacgowa-ks** [comment] 2020-06-04 22:50
I am not seeing much value in this "CF Macro" solution other then providing an unmanageable Blue/Green deployment option for a **simple** CloudFormation managed ECS service that doesn't use CodePipeline.
Without the ability to resolve SSM parameters or import values in the CF template, this further limits its usefulness.

Limitations:
- Can't update ECS service from outside of CloudFormation. I haven't tested if this impacts scaling, but it will break my lambda functions.
- No visibility of this "CodeDeploy" variation from CodeDeploy.
- No CodeDeploy style visibility or management of in-progress deployment.
- Can't use CodePipeline/CodeDeploy once this is in place.
- Can't use resolve:ssm or ImportValue within template.
- Some ECS options, such as HealthCheckGracePeriodSeconds, are not available.

After simplifying my test CF template, I am still unable to successfully update the stack. I keep running into a useless "Failed to transform template" error. I am test this with an ALB.
I want my day back.

**Comment by mattias-fjellstrom** [comment] 2020-06-11 14:14
@yubangxi I'll paste what I wrote to the AWS Support back in September 2019 when I noticed unusual behavior when using regular CodeDeploy blue/green deploy to ECS. The behavior is similar when using this new CloudFormation blue/green approach together with an NLB. 

> When testing the blue/green deployment with ECS/CodeDeploy in this setup `[API Gateway > VPC Link > NLB > ECS]` we noticed some strange behaviors. We have two listeners and two target groups. When we begin our deploy one of the target groups receives all traffic. CodeDeploy then starts up new ECS-tasks in our second target group and eventually all traffic is shifted to this target group (all at once). At that point we expected all traffic to reach the new tasks, but this is not the case. There is a long delay (1-2 minutes) before some of the traffic reaches the new target group. I say "some" because at that point the traffic seems to flip between the two target groups for a short while. A few seconds after that all traffic goes to the new target group. This is now 1.5-2.5 minutes after all traffic was supposed to only go to the new target group.

> We also tried the rollback feature in CodeDeploy. After verifying that all traffic reaches the new targets, but before the deploy finished we initiated a rollback and expected all the traffic to go to the original target group with a maximum delay of a few seconds. Once again there is a 1-2 minute delay before the traffic stops reaching the new targets. But it gets worse, after that delay all requests are now failing with 500 Internal Server Error. This goes on for a short while (5-15 seconds) until the old target group receives all traffic again.

Everything I expect to work in the scenario described above works as intended if I use an ALB instead of an NLB.

I have not tested this new CloudFormation approach enough to give a detailed description, but in one of the tests I ran I saw the same behavior with the NLB where the traffic did not reach the new targets even though the traffic was supposed to have been shifted. When I stopped the deployment by cancelling the stack update I expected a rollback to occur, but at that point it seemed like my old targets had completely disappeared and after a while I received 500 responses, similar to what I saw when using the regular CodeDeploy blue/green approach.

To me it seems like there is something with the NLB that is not compatible with blue/green deployments like this. As I mentioned in a comment above I tried blue/green deployment in a setup where I had an ALB behind the NLB, and let the NLB just send traffic to the ALB, while the ALB was involved in the blue/green deployment. In that case it worked fine. I guess it was because from the NLB's perspective the targets never changed. It's almost like the NLB has a memory that takes 1-2 minutes to update.

**Comment by yubangxi** [comment] 2020-06-11 15:36
@mattias-fjellstrom thanks for the details. This is a very good feedback and helpful. We will do some related investigation on our side and post update here if we find anything.

**Comment by avenging** [comment] 2020-06-12 18:09
> Has anyone successfully tested this using an NLB instead of an ALB?
> 
> I've adjusted the example provided in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html#blue-green-template-example to use an NLB. The template I use is available here https://github.com/mattias-fjellstrom/ecs-blue-green/blob/master/templates/ecs-blue-green-nlb.yml
> I am able to create the stack successfully, but when I perform an update (in this case modifying task cpu/memory resources to force a replacement of the task definition) I get an error saying `'CodeDeployBlueGreenHook' of type AWS::CodeDeploy::BlueGreen failed with message: Internal failure.`. Not much to go on.

I am having the exact same issue with an NLB, is NLB support pretty much Alpha?

**Comment by anugarg07** [comment] 2020-06-19 00:35
> I did use the same example you suggested. `Transform` section is in the template. The Blue/Green deployment is triggering only with TaskDefinition image changes. Changes to task definition environment variables or to cpu/memory are not triggering the deployment and stack update failing with an error above.


vladiscovery@  I verified that changes to only CPU/memory or both properties on “AWS::ECS::TaskDefinition” resource is triggering BG deployments and they are getting executed successfully without any issues, similar to “image” property update. I used “canary” style traffic-shift (the example linked in docs uses “AllAtOnce”) but that should show similar behavior.  I am sharing sample templates where only ‘Memory’ property is changed and B/G deployment  is triggered, for your reference  :

create-stack template : https://cfnda-datalake.s3.amazonaws.com/ecsbg/create-stack-canary-lc.yaml  
update-stack-template: https://cfnda-datalake.s3.amazonaws.com/ecsbg/update-stack-canary-memonly-lc.yaml 

Can you share the templates/ snippets where you saw the error when you changed CPU/memory property so that we can debug the issue you saw ? Pls share both existing and new templates.

**Comment by huynhphat22** [comment] 2020-08-13 03:30
@anugarg07 , I ran the example from the AWS doc, and changing the "Image" property of the container definition also triggers the error that @vladiscovery had...
![image](https://user-images.githubusercontent.com/19517514/90091187-f9b89580-dd4f-11ea-9968-ff1f0adbbcbe.png)

**Comment by jveldboom** [comment] 2020-08-28 15:14
@anugarg07 Thanks for the update and the example templates. I was able to get those stacks up and modify the memory property on the `AWS::ECS::TaskDefinition` resource. My issue now is the inability to update the `DesiredCount` on the `AWS::ECS::Service`. Updating that from 1 to 3 in the CFN stack throws the following error:

```
Service arn:aws:ecs:us-east-1:xxxxxxxxx:service/ecs-deployments-blue-green-ECSDemoCluster-JWxadWwdKJVq/ecs-deployments-blue-green-ECSDemoService-1X0PWPCHDGZCT failed to stabilize due to task set computed desired count 1 does not match service desired count 3. 
```

I'm also unable to update that value manually through the console. Am I missing something here?

**Comment by flyinprogrammer** [comment] 2020-09-04 18:59
Tried to get the demo deployed and working today: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html

I can get the first set of resources deployed, but upon updating the image to a new version I receive the error: Template parameters modified by transform

I can't tell if this is "working as desired" but if it is, this is useless. It should also be noted that the YAML demo Hook is missing the `ServiceRole` key. Based on the other comments here it's clear that it will be at least 6 months before something is actually tested and repeatedly works. Good luck.

**Comment by yasaswy12** [comment] 2020-09-23 05:39
@anugarg07 How do I achieve Service auto scaling with EXTERNAL deployment controller? The ECS user guide says AutoScaling is not supported with EXTERNAL controller. When I use CODE_DEPLOY as controller, the hooks section throws an error saying TaskSet is not usable with CODE_DEPLOY.

How I solve this?

**Comment by ta-takeuchi** [comment] 2020-10-26 08:13
Failed with this error when there are multiple parameters.

```
# example1 : success
Parameters:
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg1

# example2 : failure
Parameters:
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg1
  SSMActivate:
    Type: String
```

**Comment by TomLBarden** [comment] 2020-10-28 19:28
I'm getting the same error as @flyinprogrammer, even though I have no parameters in my template. I was able to successfully create the stack, but I am unable to either create a change set or update the stack due to this error. Is there at least somewhere I can be looking for more troubleshooting guidance?

**Comment by ta-takeuchi** [comment] 2020-10-29 01:29
@TomLBarden 
I used this as a reference when setting up
AWS Documentation
https://docs.aws.amazon.com/codedeploy/latest/userguide/deployments-create-ecs-cfn.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html
Classmethod, Inc Tech blog
https://dev.classmethod.jp/articles/cloudformation-fargate-bluegreen/

**Comment by TomLBarden** [comment] 2020-10-29 12:27
Unfortunately none of this has helped @ta-takeuchi 

The issue itself is so vague and I can't find any documentation as to what's causing it.

**Comment by JeremySB** [comment] 2020-11-29 06:19
We've identified an issue with the Blue/Green transform involving boolean parsing which leads to those `Template parameters modified by transform` errors and are working with the CodeDeploy team to resolve it. The failures I've encountered are from attempts to use NoEcho parameters in Blue/Green templates which isn't supported - if you have other sample templates that cause the same error feel free to post them and I'll try to reproduce. Thanks!

**Comment by BhrikutyAggarwal** [comment] 2020-12-11 10:15
Hey @JeremySB , I am facing same error **Template parameters modified by transform** by updating below template.
https://github.com/BhrikutyAggarwal/ECS-BG/blob/main/ECS-BG-template.json

**Comment by CelesteComet** [comment] 2021-01-13 03:13
Can we reopen this? I am hitting an internal error problem when just changing the image property in my task definition. This basically makes the CF a one time usage without the ability to update anything.

**Comment by CelesteComet** [comment] 2021-01-13 07:52
Here is a link to the gist. I am using ALB and running into the mysterious internal error problem.
https://gist.github.com/gucolin/b9b108e5bcea513f9c704c576595f174

**Comment by ta-takeuchi** [comment] 2021-01-22 10:00
Blue/Green conversion issues, including Boolean parsing, still seem to occur.
I have created a template that converts Parameters to boolean in Conditions and uses "! If" in the resource properties.
The stack was created successfully, but the Image update encountered an internal error.
`CodeDeployBlueGreenHook of type AWS::CodeDeploy::BlueGreen failed with message: Internal Failure`

I shared the template with the support team. Best regards.

**Comment by adrianwilson** [comment] 2021-04-14 22:16
If it helps anyone, I was getting `Template parameters modified by transform` on a nested stack. Flipping the nested stack to a construct resolved the issue. Might be worth investigating if there's an issue with using AWS::CodeDeployBlueGreen on nested stacks?

**Comment by chezhuo1994** [comment] 2021-06-17 06:36
Facing "Failed to transform template" error, anyone has fixed it?

**Comment by ta-takeuchi** [comment] 2021-06-18 02:32
Issue is not solved yet.
I'm doing this...
1. Update stack directly with template with dummy resources added.
2. Update with template with dummy resources removed.
3. Deploying with a template with changed ImageID.
