### ISSUE TITLE
[Dynamic References] ssm and ssm-secure: Add support for getting the latest version of a parameter

### ISSUE THREAD

**Issue by swlasse** [aws-cloudformation/aws-cloudformation-coverage-roadmap#296] opened 2019-12-09 15:09 UTC
## 1. [Dynamic References] ssm and ssm-secure: Add support for getting the latest version of a parameter

Using the `ssm` and `ssm-secure` dynamic references, parameters from the SSM Parameter Store can currently only be referenced by explicitly stating which exact version to retrieve.

From the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm) (emphasis mine):

> **SSM Parameters**
Use the ssm dynamic reference to include values stored in the Systems Manager Parameter Store of type String or StringList in your templates.
(...)
**version**
An integer that specifies the version of the parameter to use. **You must specify the exact version. You cannot currently specify that AWS CloudFormation use the latest version of a parameter.**

This feature request is about allowing one to retrieve the latest version of an SSM Parameter using the `ssm` and `ssm-secure` dynamic references.

## 2. Scope of request 

The `ssm` and `ssm-secure` CloudFormation Dynamic References.

## 3. Expected behavior

I imagine this can be accomplished in different ways. Using an example from the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings), possible solutions could be:

#### Retrieve the latest version (by not specifying a version number)
```
MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: 'MyUserName'
      LoginProfile:
        Password: '{{resolve:ssm-secure:IAMUserPassword}}'
```

#### Retrieve the latest version (by using a keyword)
```
MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: 'MyUserName'
      LoginProfile:
        Password: '{{resolve:ssm-secure:IAMUserPassword:$Latest}}'
```

## 4. Suggest specific test cases

- Create a parameter with multiple versions, and ensure that CloudFormation is able to fetch the latest version during stack and change set operations.
-> This should work for the `ssm` dynamic reference when fetching `String` and `StringList` parameters.
 -> This should work for the `ssm-secure` dynamic reference when fetching `SecureString` parameters.

#### CloudFormation `ssm` dynamic reference documentation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm

> **SSM Parameters**
Use the ssm dynamic reference to include values stored in the Systems Manager Parameter Store of type String or StringList in your templates.
(...)
**version**
An integer that specifies the version of the parameter to use. You must specify the exact version. You cannot currently specify that AWS CloudFormation use the latest version of a parameter.

#### CloudFormation `ssm-secure` dynamic reference documentation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings

> **SSM Secure String Parameters**
Use the ssm-secure dynamic reference pattern to specify AWS Systems Manager SecureString type parameters in your templates.
(...)
**version**
An integer that specifies the version of the parameter to use. You must specify the exact version. You cannot currently specify that AWS CloudFormation use the latest version of a parameter.

## 6. Category (required)

Management & Governance (Systems Manager Parameter Store)
Management & Governance (CloudFormation Dynamic References)

**Comment by PatMyron** [comment] 2019-12-09 17:12
duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/75

**Closed by PatMyron** 2019-12-09 17:12 UTC

**Comment by swlasse** [comment] 2019-12-10 07:14
@PatMyron ah, sorry, you are right. This is indeed a duplicate. I have +1'ed the original issue instead.
