### ISSUE TITLE
AWS::RDS::DBInstance-DeletionPolicy

### ISSUE THREAD

**Issue by seb-steuer** [aws-cloudformation/aws-cloudformation-coverage-roadmap#269] opened 2019-11-20 14:53 UTC
## 2. Scope of request 
Add support for referencing parameter for DeletionPolicy

## 3. Expected behavior
When referencing parameter that is of String type for DeletionPolicy CFormation should accept it if the value is supported.
Instead a message is displayed when trying to create a stack:
Template validation error: Template format error: Every DeletionPolicy member must be a string.

## 4. Suggest specific test cases

Samples:
`
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "RDS parameterized deletion policy testing",
	"Parameters": {
		"RDSDeletionPolicy": {
			"Description": "Selectible deletion policy testing",
			"Type": "String",
			"Default": "Snapshot",
			"AllowedValues": [ "Snapshot", "Delete", "Retain" ]
		},
		"DBSubnetGroup": {
			"Description": "Subnet Group to use for RDS",
			"Type": "String"
		},
		"RDSSecurityGroup": {
			"Description": "Security Group to use for RDS",
			"Type": "String"
		}
	},
	"Resources": {
		"DB": {
			"Type": "AWS::RDS::DBInstance",
			"DeletionPolicy": { "Ref": "RDSDeletionPolicy" },
			"Properties": {
				"AllocatedStorage": 10,
				"AutoMinorVersionUpgrade": false,
				"BackupRetentionPeriod": 0,
				"CopyTagsToSnapshot": true,
				"DBInstanceClass": "db.t3.micro",
				"DBSubnetGroupName": { "Ref": "DBSubnetGroup" },
				"Engine": "postgres",
				"EngineVersion": "9.6.11",
				"MasterUsername": "postgres",
				"MasterUserPassword": "T35t.1n6",
				"StorageType": "gp2",
				"MultiAZ": "false",
				"VPCSecurityGroups": [ { "Ref": "RDSSecurityGroup" } ],
				"Tags": [
					{ "Key": "Name", "Value": "TEMP TESTING CF" }
				]
			}
		}
	}
}
`

**Comment by PatMyron** [comment] 2019-11-20 19:10
closing as duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/162

**Closed by PatMyron** 2019-11-20 19:10 UTC
