### ISSUE TITLE
AWS::S3::Bucket-Rule-ExpiredObjectDeleteMarker

### ISSUE THREAD

**Issue by cccassidy** [aws-cloudformation/aws-cloudformation-coverage-roadmap#132] opened 2019-08-18 23:46 UTC
## 2. Scope of request 
Add ExpiredObjectDeleteMarker option to S3 lifecycle policy specifications.

## 3. Expected behavior
Enable/Disable remove of expired object delete markers

```
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteMarker
            Prefix: "/"
            Status: Enabled
            ExpiredObjectDeleteMarker: true
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Storage (S3, EFS, Backup...)

**Comment by rectalogic** [comment] 2020-02-11 20:18
@TheDanBlanco Is there any way to get this onto the roadmap?

**Comment by TheDanBlanco** [comment] 2020-02-11 21:35
we prioritize items mostly based on +1's. you can almost always accurately track which items we're looking at putting on our roadmap by filtering for +1's.

**Comment by benkehoe** [comment] 2020-02-11 21:42
To clarify, by +1s you mean positive reaction emojis on the issue?

**Comment by TheDanBlanco** [comment] 2020-02-11 21:44
yep!

**Comment by lkr2des** [comment] 2020-03-10 17:27
+1

**Comment by arvidwarnecke0042** [comment] 2020-03-20 14:43
+1

**Comment by cesarrp** [comment] 2020-03-26 00:38
+1

**Comment by joaobodingbaner** [comment] 2020-03-26 00:39
+1

**Comment by angelarw** [comment] 2020-03-26 14:05
+1

**Comment by benkehoe** [comment] 2020-03-26 14:08
It's usually better etiquette to use reactions (the "+😀" button on a comment) than to have lots of individual people clutter up the comments (and notifications) with "+1" comments. And when you put 👍 on an issue, it's easier to see the support for an issue right up front!

**Comment by TheDanBlanco** [comment] 2020-03-26 15:22
ben's right! i'll be cleaning up "+1" comments as they generally only serve to clutter any discussions.

**Comment by dflanzer-s1** [comment] 2020-04-21 16:59
@TheDanBlanco do you know, if you're maintaining a bucket via cloudformation, and you go in and set the ExpiredObjectDeleteMarker checkbox in the console, will that cause stack drift? Or since it's not CF-able, it will avoid interference?

**Comment by cccassidy** [comment] 2020-04-21 17:03
@dflanzer-s1 What I've seen is subsequent updates to the S3 bucket will remove any manual lifecycle policies you enter from the console.

**Comment by LaikaN57** [comment] 2020-05-02 06:50
@dflanzer-s1 Just confirmed, drift detection will detect a drift.
![image](https://user-images.githubusercontent.com/206373/80857344-5c08e280-8c06-11ea-8574-c2e2d3c8adfb.png)

**Comment by markatthrive** [comment] 2020-06-25 08:41
+1 from me; this is a real pain point for us currently.

**Comment by jonathanwcrane** [comment] 2020-06-30 13:45
+1

**Comment by LaikaN57** [comment] 2020-06-30 23:14
@markatthrive @jonathanwcrane Can you please react +1 to the issue as well if you have not done so. They only use that to determine issue sort order. Comments are ignored.

**Comment by Ricapar** [comment] 2020-07-20 18:01
This is a pretty critical setting on S3 especially if you're using it as a backend for Athena or other systems that are querying the bucket.

I have a lifecycle policy that expires old versions to keep the bucket clean, but I'm left with an abundance of delete-markers that slow down s3:List* performance significantly.

For now I'm left with no choice than to drift the stack by modifying the lifecycle rule.

It's been nearly a year since this was submitted and this item is #2 on the most +1'd issues on the tracker. Is this going to happen?

**Comment by vincent-dm** [comment] 2020-08-19 00:03
+1

**Comment by efenderbosch** [comment] 2020-11-17 16:00
Now 15 months old and the highest +1'd issue. Any update on roadmap?

**Comment by LYLeon** [comment] 2021-01-14 09:49
+1

**Comment by harryxp** [comment] 2021-03-23 18:39
It's not great that CloudFormation users have to resort to custom resources for something that AWS API supports.  Glad to see it's on the roadmap now!

**Comment by MikeKroell** [comment] 2021-03-24 17:30
+1

**Comment by benbridts** [comment] 2021-03-24 21:59
@MikeKroell @LYLeon @jonathanwcrane @markatthrive 

If you react with the 👍  button to the original issue, (the first comment, click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers), but cannot be easily counted as a vote for an issue. Thus It's generally better to vote than to comment with "+1". To keep up to date, you can also add yourself as a watcher.

**Comment by markatthrive** [comment] 2021-03-25 08:50
@LaikaN57 @benbridts Yes, I already upvoted that when I posted my comment. 194 upvotes and we're still waiting.

![just-waiting](https://user-images.githubusercontent.com/67412937/112445201-ca86ef80-8d46-11eb-8bad-9edaf983ab0b.gif)

**Comment by jonathanwcrane** [comment] 2021-03-25 13:34
> 
> 
> we prioritize items mostly based on +1's. you can almost always accurately track which items we're looking at putting on our roadmap by filtering for +1's.

I just sorted all the issues in this repo by +1s and this issue is in first place.  All 5 of the top 5 are from 2019.  Sounds like AWS makes progress on requested features about as quickly as container ships can currently navigate the Suez Canal.

**Comment by craigataws** [comment] 2021-03-26 21:47
We are actively working on releasing (moved item to "Coming Soon").  While I can't provide an exact date for official release, it is targeted for Q2.

**Comment by tstibbs** [comment] 2021-03-29 10:10
@craigataws will that change in cloudformation come with a corresponding change in the high-level constructs in CDK? Or will there then have to be a separate ticket logged against CDK?

**Comment by richardhboyd** [comment] 2021-04-06 09:21
@tstibbs There will most likely need to be a change to the high-level CDK Construct to support a new CloudFormation resource.

**Comment by urda** [comment] 2021-04-25 20:51
Is this still on track for a `Q2` release?

**Comment by craigataws** [comment] 2021-04-26 16:24
@urda, yes

**Comment by icalvete** [comment] 2021-05-03 07:32
+1

**Comment by rohits-spec** [comment] 2021-05-17 21:41
Launched on 5/14. Resolving the issue.

**Closed by rohits-spec** 2021-05-17 21:41 UTC
Labels: storage

**Comment by joebernard** [comment] 2021-05-18 12:21
For anyone curious the new docs are here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html#cfn-s3-bucket-rule-expiredobjectdeletemarker

**Comment by LaikaN57** [comment] 2021-05-18 21:52
Thank you to the community for upvoting this and holding strong. And thank you to AWS for getting this across the line! Good work all.

**Comment by noslowerdna** [comment] 2022-03-18 14:58
@craigataws The "Expected Behavior" example YAML seems incomplete. That resulted in this error attempting to update the CloudFormation stack for a bucket:

> "At least one of [ExpirationDate,ExpirationInDays,AbortIncompleteMultipartUpload,Transition,Transitions,NoncurrentVersionExpirationInDays,NoncurrentVersionTransition,NoncurrentVersionTransitions,NoncurrentVersionExpiration] needs to be specified"

**Comment by srinadhbh** [comment] 2022-12-07 18:19
+1
