### ISSUE TITLE
AWS::IAM::User (Allow tags)

### ISSUE THREAD

**Issue by briandaltilio** [aws-cloudformation/aws-cloudformation-coverage-roadmap#236] opened 2019-10-22 15:18 UTC
We use cloudformation to create IAM users.  We manage the lifecycle of the user based on tag values.  We need to create the tags using other methods, such as custom resources.  Native support for tagging would be helpful.

**Comment by PatMyron** [comment] 2019-10-22 21:37
closing as duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/69

**Closed by PatMyron** 2019-10-22 21:37 UTC
