### ISSUE TITLE
AWS::EC2::VPCEndpoint-Tags support missing

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/aws-cloudformation-coverage-roadmap#202] opened 2019-10-04 04:55 UTC
## 1. Title 
AWS::EC2::VPCEndpoint-Tags

## 2. Scope of request 
AWS::EC2::VPCEndpoint does not support tagging, however VPCEndpoints can be tagged using the EC2 CreateTags and DeleteTags API, the VPCEndpoint CloudFormation resource should support management of these tags in the same manner as some other EC2 resources already support.

## 3. Expected behavior
Tags specified on the resource in the CloudFormation template should be created / updated / deleted on the actual EC2 resource 

## 4. Suggest specific test cases
1. Set a Name Tag on the VPC Endpoint  in the CloudFormation template  and ensure it's value is visible when making a DescribeTags API call for the VPC Endpoint resource
2. Update the Name Tag on the VPC Endpoint  in the CloudFormation template  and ensure it's new value is reflected when making a DescribeTags API call for the VPC Endpoint resource
3. Delete the Name Tag on the VPC Endpoint in the CloudFormation template  and ensure it's new value is reflected when making a DescribeTags API call for the VPC Endpoint resource

## 5. Helpful Links to speed up research and evaluation

EC2 Resource Tagging API Methods
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html
* https://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-or-update-tags.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteTags.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeTags.html

AWS::EC2::Instance Tags attribute - it would be good if the behaviour and syntax was consistent with this
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-tags

## 6. Category
* Compute
* Networking & Content

**Comment by TheDanBlanco** [comment] 2019-10-09 21:13
looks like a duplicate of https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/196 - if this isn't the case please re-open this issue!

**Closed by TheDanBlanco** 2019-10-09 21:13 UTC

**Comment by ajoga** [comment] 2019-10-15 08:39
@TheDanBlanco Could I suggest you to re-open this one which is way more detailed than #196 ? This one is scoping way more the work expected, and from my perspective I can see that it isn't including in its scope what I'm looking for, therefore I'm going to open another request... That you could also see as a duplicate of #196. Thanks.

**Comment by davidgatti** [comment] 2024-07-04 17:09
2024...

**Comment by andre-tui** [comment] 2024-08-07 12:29
though I was going crazy, nothing worked, and then I saw @davidgatti 's  comment. 
Is there a timeline for fix?

**Comment by davidgatti** [comment] 2026-01-28 15:58
2026...

**Comment by gatewaynovice** [comment] 2026-01-28 18:01
> 2026...
Tags are available now: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-ec2-vpcendpoint.html
